# Generated by Django 2.2.1 on 2019-08-21 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('nik', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tgl_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('LAKI-LAKI', 'Laki-Laki'), ('PEREMPUAN', 'Perempuan')], max_length=20)),
                ('alamat', models.CharField(max_length=100)),
                ('rt', models.CharField(max_length=3)),
                ('rw', models.CharField(max_length=3)),
                ('desa_kelurahan', models.CharField(max_length=20)),
                ('kecamatan', models.CharField(max_length=20)),
                ('kabupbaten_kota', models.CharField(max_length=20)),
                ('provinsi', models.CharField(max_length=20)),
                ('agama', models.CharField(choices=[('ISLAM', 'Islam'), ('KRISTEN KATOLIK', 'Kristen Katolik'), ('KRISTEN PROTESTAN', 'Kristen Protestan')], max_length=20)),
                ('status_perkawinan', models.CharField(choices=[('KAWIN', 'Kawin'), ('BELUM KAWIN', 'Belum Kawin'), ('JANDA', 'Janda'), ('DUDA', 'Duda')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pegawai', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pegawai', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatPendidikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('SWASTA', 'SWASTA'), ('NEGERI', 'NEGERI')], max_length=20)),
                ('jurusan_prodi', models.CharField(blank=True, max_length=50, null=True)),
                ('akreditasi', models.CharField(choices=[('SWASTA', 'SWASTA'), ('NEGERI', 'NEGERI')], max_length=20)),
                ('nama_instansi', models.CharField(max_length=50)),
                ('alamat_instansi', models.CharField(max_length=200)),
                ('no_ijazah', models.CharField(max_length=50)),
                ('gelar_depan', models.CharField(blank=True, max_length=10, null=True)),
                ('gelar_belakang', models.CharField(blank=True, max_length=10, null=True)),
                ('tgl_ijazah', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_riwayat_pendidikan', to=settings.AUTH_USER_MODEL)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pendidikan', to='pegawai.Pegawai')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_riwayat_pendidikan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatKeluarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('nip', models.CharField(blank=True, max_length=18, null=True)),
                ('nama', models.CharField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tgl_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('LAKI-LAKI', 'Laki-Laki'), ('PEREMPUAN', 'Perempuan')], max_length=20)),
                ('pekerjaan', models.CharField(max_length=100)),
                ('institusi', models.CharField(max_length=100)),
                ('status_perkawinan', models.CharField(choices=[('KAWIN', 'Kawin'), ('BELUM KAWIN', 'Belum Kawin'), ('JANDA', 'Janda'), ('DUDA', 'Duda')], max_length=20)),
                ('no_akte', models.CharField(max_length=20)),
                ('tgl_akte', models.DateField()),
                ('hubungan', models.CharField(max_length=20)),
                ('status_hidup', models.CharField(choices=[('HIDUP', 'Hidup'), ('MATI', 'Mati')], max_length=10)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_riwayat_keluarga', to=settings.AUTH_USER_MODEL)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_keluarga', to='pegawai.Pegawai')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_riwayat_keluarga', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
